name: Main Workflow

on:
  workflow_dispatch: # Allow manual trigger
  push:
    branches:
      - 'master'
    paths:
      - './README.md'

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: Checkout and upload Readme to Notion
    steps:
      - uses: actions/checkout@main
      - name: Sync README to Notion
        uses: Elioby/notion-sync-md-page@main
        with:
          token: ${{ secrets.NOTION_TOKEN }}
          page: ${{ secrets.NOTION_PAGE_ID }}
          mdFile: './README.md'
